system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: BlockServer
  dir: logs
db:
  user: root
  password: Dt1052323212.
  host: 192.168.5.129
  port: 3306
  db: blogx
  debug: false
  source: mysql
db1:
  user: root
  password: Dt1052323212.
  host: 192.168.5.129
  port: 3306
  db: blogx
  debug: false
  source: mysql
jwt:
  expire: 3
  secret: xxx
  issuer: danta
redis:
  addr: 192.168.5.129:6379
  password: ""
  db: 1
site:
  siteInfo:
    title: danta博客1
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 蛋挞
    icon: /yyy.png
    webPath: uploads/index.html
  seo:
    keywords: 蛋挞
    description: 蛋挞好吃
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: true
  indexRight:
    list: []
  article:
    noExamine: true
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 1052323212@qq.com
  authCode: kotzxppdzglxbeja
  sendNickname: 蛋挞博客
  ssl: true
  tls: false
qq:
  appID: "123456789"
  appKey: ""
  redirect: http://xxxxxxxx
qiNiu:
  enable: true
  accessKey: yc0W3Q6mupl-PqEoj_z1xmq6ood700G0-3pdq3Uo
  secretKey: J1Pu3J5Vo9prjykzOj3dfie_wjIsz1IsLQAWYKLx
  bucket: dantablog
  uri: http://spcsowzbl.hn-bkt.clouddn.com
  region: z2
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: njNJSDNKGNKSDNdmgsdoggs
  nickname: 蛋挞
  avatar: /xxx/xx
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images01
